### ISSUE TITLE
How could I recreate this?

### ISSUE THREAD

**Issue by devxan** [DoubleGremlin181/DoubleGremlin181#1]
Hello @DoubleGremlin181! 
I really like this game of tic-tac-toe and I want to recreate it on my Github profile.  
How would I add it to my own readme? 
(I would also want to make the tic-tac-toe board smaller and change the icons if that would be possible.)

**Comment by DoubleGremlin181** [comment]
Hey @devxan 

[Here](https://kavishhukmani.me/github-profile-interactive-readme-tutorial/) is a link to a guide I wrote about how to create a similar project. It should give you a good understanding about how it works and you should enable you to implement your own ideas easily.

As for resizing the icons, it should be possible if you use smaller sized images. (There might also be a way to do so via HTML tags but I am not sure if GitHub supports it within tables.)
You can easily change the icons to anything you like. They are located in assets folder.

Happy coding!
