### ISSUE TITLE
bug on profile

### ISSUE THREAD

**Issue by Shoaib19** [DoubleGremlin181/DoubleGremlin181#6]
Your tic tac toe keeps crashing when I try to play it plus the black color of marks is not visible on GitHub dark mode change the color scheme.

**Comment by DoubleGremlin181** [comment]
It seems like the website I was using to shorten links and count clicks isn't maintained anymore. I'm looking for alternatives as I really want to avoid spinning something up myself.

**Comment by Shoaib19** [comment]
when you resolve let me know I will close the issue.
I am ROR dev If you think I can help provide me some context.
thanks

**Comment by DoubleGremlin181** [comment]
I've updated the repo to use a new link shortner [Linkly](https://linklyhq.com/)
